"""Remove mobile_number and item_name from recommendations

Revision ID: c92835680819
Revises: 6565096c8c78
Create Date: 2025-09-15 12:16:20.600815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c92835680819'
down_revision: Union[str, Sequence[str], None] = '6565096c8c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommendations', 'mobile_number')
    op.drop_column('recommendations', 'item_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('recommendations', sa.Column('mobile_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
